### ISSUE TITLE
Error throw

### ISSUE THREAD

**Issue by arkolesen** [bitcoincashjs/bchaddrjs#6]
Hi!
Thanks a lot for your library. It was implemented in time!

I've got one idea
Why do u throw error if f.e. BCH address was invalid?
Validation method is named as isCashAddress, i think it's better (in case of invalid address) return just false
What do u think?
Regards

**Comment by ealmansi** [comment]
All functions in the API require that the argument be a valid BCH address, and throw an exception if this is not the case. I can see now how this may not be fully intuitive in the case of `isCashAddress`, where returning false would be reasonable. However, it is also useful to be able to distinguish between two separate cases: i) the input is not a valid address in any format, ii) the input is simply not in cashaddr format.

I'll close the issue for now since adding a breaking change at this point seems unnecessary. If a new BCH address format is created and warrants a new version, we can reconsider changing the API to follow your suggestion.
